# Generated by Django 5.0 on 2024-01-16 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MMA', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fight',
            name='event',
        ),
        migrations.RemoveField(
            model_name='fight',
            name='fighter1',
        ),
        migrations.RemoveField(
            model_name='fight',
            name='fighter2',
        ),
        migrations.RemoveField(
            model_name='fight',
            name='weight_class',
        ),
        migrations.RemoveField(
            model_name='fight',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='weight_class',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='fight',
        ),
        migrations.DeleteModel(
            name='Fighter',
        ),
        migrations.DeleteModel(
            name='WeightClass',
        ),
    ]
